name: Fork Pull Request CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      # You can add other non-sensitive checks here